### ISSUE TITLE
Incompatible with GWT 2.7.0-Beta1

### ISSUE THREAD

**Issue by rdwallis** [seanchenxi/gwt-storage#4]
gwt-storage version: 1.2.1-SNAPSHOT

Truncated stack trace:

```
[INFO] Caused by: java.lang.NoSuchMethodError: com.google.gwt.user.rebind.rpc.SerializableTypeOracleBuilder.<init>(Lcom/google/gwt/core/ext/TreeLogger;Lcom/google/gwt/core/ext/PropertyOracle;Lcom/google/gwt/core/ext/GeneratorContext;)V
[INFO]  at com.seanchenxi.gwt.storage.rebind.StorageTypeSerializerGenerator.buildSerializableTypeOracle(StorageTypeSerializerGenerator.java:89)
[INFO]  at com.seanchenxi.gwt.storage.rebind.StorageTypeSerializerGenerator.generateIncrementally(StorageTypeSerializerGenerator.java:61)
```

I'll do a PR when I have the fix for this.

**Comment by aagooru** [comment]
@rdwallis  @seanchenxi 

How can i get a copy of 1.3.0-SNAPSHOT for this fix?  Or do i need to use the 1.3.1 JAR?

Thanks!

**Comment by seanchenxi** [comment]
@aagooru you can just use version 1.3.0

**Comment by nishi2874** [comment]
I get this error :
[INFO]          [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:121)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:296)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO] 	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:67)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO] 	at com.google.gwt.dev.jjs.ast.JDeclarationStatement.traverse(JDeclarationStatement.java:49)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:95)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:351)
[INFO] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:149)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:145)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:600)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:569)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1505)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:870)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1305)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1038)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.precompile(JavaToJavaScriptCompiler.java:954)
[INFO] 	at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.precompile(MonolithicJavaToJavaScriptCompiler.java:303)
[INFO] 	at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:38)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:286)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
[INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:206)
[INFO] 	at com.google.gwt.dev.codeserver.Recompiler.doCompile(Recompiler.java:333)
[INFO] 	at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:161)
[INFO] 	at com.google.gwt.dev.codeserver.Recompiler.recompile(Recompiler.java:119)
[INFO] 	at com.google.gwt.dev.codeserver.Outbox.recompile(Outbox.java:128)
[INFO] 	at com.google.gwt.dev.codeserver.JobRunner.recompile(JobRunner.java:81)
[INFO] 	at com.google.gwt.dev.codeserver.JobRunner.access$100(JobRunner.java:34)
[INFO] 	at com.google.gwt.dev.codeserver.JobRunner$2.run(JobRunner.java:73)
[INFO] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[INFO] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO] Caused by: java.lang.NoSuchMethodError: com.google.gwt.user.rebind.rpc.SerializableTypeOracleBuilder.<init>(Lcom/google/gwt/core/ext/TreeLogger;Lcom/google/gwt/core/ext/PropertyOracle;Lcom/google/gwt/core/ext/GeneratorContext;)V
[INFO] 	at com.googlecode.serialization.JsonSerializationGenerator.generate(JsonSerializationGenerator.java:83)
[INFO] 	at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
[INFO] 	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:760)
[INFO] 	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:160)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:79)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:276)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:265)
[INFO] 	at com.google.gwt.dev.DistillerRebindPermutationOracle.getAllPossibleRebindAnswers(DistillerRebindPermutationOracle.java:87)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:485)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:443)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleMagicMethodCall(UnifyAst.java:576)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.endVisit(UnifyAst.java:306)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:248)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
[INFO] 	... 47 more
[INFO]             [ERROR] at LibraryMenuNav.java(128): GWT.create(StorageJsonSerializationFactory.class)
[INFO]             [ERROR] at LibraryMenuNav.java(128): (StorageJsonSerializationFactory) GWT.create(StorageJsonSerializationFactory.class)
[INFO]        

Project dependency list
[INFO] +- org.springframework:spring-expression:jar:3.1.2.RELEASE:compile
[INFO] +- org.springframework:spring-tx:jar:3.1.2.RELEASE:compile
[INFO] |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] +- org.springframework:spring-aspects:jar:3.1.2.RELEASE:compile
[INFO] |  \- org.springframework:spring-context-support:jar:3.1.2.RELEASE:compile
[INFO] +- org.springframework:spring-webmvc:jar:3.1.2.RELEASE:compile
[INFO] +- org.springframework:spring-asm:jar:3.1.2.RELEASE:compile
[INFO] +- org.springframework:spring-core:jar:3.1.2.RELEASE:compile
[INFO] |  \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] +- org.springframework:spring-beans:jar:3.1.2.RELEASE:compile
[INFO] +- org.springframework:spring-aop:jar:3.1.2.RELEASE:compile
[INFO] +- org.springframework:spring-context:jar:3.1.2.RELEASE:compile
[INFO] +- org.springframework:spring-web:jar:3.1.2.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-config:jar:3.1.1.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-core:jar:3.1.1.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-taglibs:jar:3.1.1.RELEASE:compile
[INFO] |  \- org.springframework.security:spring-security-acl:jar:3.1.1.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-web:jar:3.1.1.RELEASE:compile
[INFO] |  \- org.springframework:spring-jdbc:jar:3.0.7.RELEASE:compile
[INFO] +- org.aspectj:aspectjweaver:jar:1.7.0:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.1.0:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.1.0:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.1.0:compile
[INFO] +- com.allen-sauer.gwt.dnd:gwt-dnd:jar:3.2.0:compile
[INFO] +- com.google.gwt.inject:gin:jar:2.1.2:compile
[INFO] |  \- com.google.inject.extensions:guice-assistedinject:jar:3.0:compile
[INFO] +- com.google.inject:guice:jar:3.0:compile
[INFO] |  \- javax.inject:javax.inject:jar:1:compile
[INFO] +- com.google.inject.extensions:guice-multibindings:jar:3.0:compile
[INFO] +- com.google.code.gwt-dnd:gwt-dnd:jar:2.5.6:compile
[INFO] +- com.gwtplatform:gwtp-mvp-client:jar:1.4:compile
[INFO] |  +- com.gwtplatform:gwtp-clients-common:jar:1.4:compile
[INFO] |  +- com.google.gwt:gwt-user:jar:2.7.0:compile
[INFO] |  |  +- javax.validation:validation-api:jar:1.0.0.GA:compile
[INFO] |  |  \- javax.validation:validation-api:jar:sources:1.0.0.GA:compile
[INFO] |  +- com.google.gwt:gwt-dev:jar:2.7.0:compile
[INFO] |  |  +- org.ow2.asm:asm:jar:5.0.3:compile
[INFO] |  |  +- org.ow2.asm:asm-util:jar:5.0.3:compile
[INFO] |  |  |  \- org.ow2.asm:asm-tree:jar:5.0.3:compile
[INFO] |  |  \- org.ow2.asm:asm-commons:jar:5.0.3:compile
[INFO] |  \- org.apache.velocity:velocity:jar:1.7:compile
[INFO] +- com.gwtplatform:gwtp-mvp-shared:jar:1.3.1:compile
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.6.1:provided
[INFO] |  \- log4j:log4j:jar:1.2.16:provided
[INFO] +- org.slf4j:slf4j-api:jar:1.6.1:provided
[INFO] +- com.seanchenxi.gwt:gwt-storage:jar:1.3.0:compile
[INFO] +- com.google.gwt:gwt-servlet:jar:2.7.0:compile
[INFO] +- org.restlet.jse:org.restlet:pom:2.1-M6:compile
[INFO] |  \- org.osgi:org.osgi.core:jar:4.0.0:compile
[INFO] +- org.restlet.jse:org.restlet:jar:2.1-M6:compile
[INFO] +- org.restlet.jse:org.restlet.ext.simple:jar:2.1-M6:compile
[INFO] |  \- org.simpleframework:simple:jar:4.1.21:compile
[INFO] +- org.restlet.jse:org.restlet.ext.json:jar:2.1-M6:compile
[INFO] |  \- org.restlet.jse:org.restlet.lib.org.json:jar:2.0:compile
[INFO] +- org.restlet.jse:org.restlet.ext.ssl:jar:2.1-M6:compile
[INFO] |  \- org.jsslutils:jsslutils:jar:1.0.5:compile
[INFO] +- org.restlet.jse:org.restlet.ext.net:jar:2.1-M6:compile
[INFO] +- org.restlet.jse:org.restlet.ext.html:jar:2.1-M6:compile
[INFO] +- commons-lang:commons-lang:jar:2.6:compile
[INFO] +- com.tractionsoftware:gwt-traction:jar:1.5.9:compile
[INFO] |  +- org.google:gwt-traction:jar:1.5.2:compile
[INFO] |  +- commons-io:commons-io:jar:1.3.2:compile
[INFO] |  \- org.apache.httpcomponents:httpmime:jar:4.2:compile
[INFO] +- com.bramosystems.oss.player:bst-player-api:jar:1.3:compile
[INFO] +- org.json:json:jar:20090211:compile
[INFO] |  +- org.google:gwt-traction:jar:1.5.2:compile
[INFO] |  +- commons-io:commons-io:jar:1.3.2:compile
[INFO] |  \- org.apache.httpcomponents:httpmime:jar:4.2:compile
[INFO] +- com.bramosystems.oss.player:bst-player-api:jar:1.3:compile
[INFO] +- org.json:json:jar:20090211:compile
[INFO] +- org.apache.httpcomponents:httpcore:jar:4.2.2:compile
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.2:compile
[INFO] +- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] +- commons-codec:commons-codec:jar:1.6:compile
[INFO] +- com.googlecode.gwt-cropper:gwt-crop:jar:0.5.1:compile
[INFO] +- com.google.code:GwtEarth3:jar:1.0:compile
[INFO] +- com.itextpdf:itextpdf:jar:5.4.3:compile
[INFO] +- code.google.com:gwt-print-it:jar:1.13:compile
[INFO] +- com.googlecode.gwtupload:gwtupload:jar:1.0.3:compile
[INFO] |  \- commons-fileupload:commons-fileupload:jar:1.3.1:compile
[INFO] +- code.google.com:gwt-serialization:jar:1.0:compile
[INFO] +- com.googlecode.gwtquery:gwtquery:jar:1.4.3:provided
[INFO] |  \- com.google.gwt:gwt-elemental:jar:2.7.0:provided
[INFO] +- com.google.gwt:gwt-incubator:jar:2.0.1:compile
[INFO] +- com.samaxes.maven:minify-maven-plugin:jar:1.7:compile
[INFO] \- com.google.code.maven-replacer-plugin:replacer:jar:1.5.3:compile
[INFO]    +- org.apache.maven:maven-plugin-api:jar:3.0.3:compile
[INFO]    |  +- org.apache.maven:maven-model:jar:3.0.3:compile
[INFO]    |  |  \- org.codehaus.plexus:plexus-utils:jar:2.0.6:compile
[INFO]    |  +- org.apache.maven:maven-artifact:jar:3.0.3:compile
[INFO]    |  \- org.sonatype.sisu:sisu-inject-plexus:jar:2.1.1:compile
[INFO]    |     +- org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[INFO]    |     +- org.codehaus.plexus:plexus-classworlds:jar:2.4:compile
[INFO]    |     \- org.sonatype.sisu:sisu-inject-bean:jar:2.1.1:compile
[INFO]    |        \- org.sonatype.sisu:sisu-guice:jar:no_aop:2.9.4:compile
[INFO]    +- org.apache.ant:ant:jar:1.8.2:compile
[INFO]    |  \- org.apache.ant:ant-launcher:jar:1.8.2:compile
[INFO]    \- xerces:xercesImpl:jar:2.8.0:compile
[INFO]       \- xml-apis:xml-apis:jar:1.3.03:compile

Can you please help?

**Comment by seanchenxi** [comment]
@nishi2874 I'll check this

**Comment by nishi2874** [comment]
@seanchenxi 

Thank you . Waiting for a solution

**Comment by seanchenxi** [comment]
@nishi2874 
Please look at your stack trace carefully, the "java.lang.NoSuchMethodError" is happened in class **com.googlecode.serialization.JsonSerializationGenerator**. And it is **NOT** my framework's class. 
I think you got wrong place to ask for support.

I also re-verified gwt-storage version 1.3.0. This issue was correctly fixed.

**Comment by nishi2874** [comment]
@seanchenxi 

Thanks for the reply. I was going through the dependency lists and here is what I found:

 com.googlecode.gwt-cropper:gwt-crop:0.5.1" level="project" /> -- http://mvnrepository.com/artifact/com.googlecode.gwt-cropper/gwt-crop/0.5.1 depends on gwt-user 2.4
 com.allen-sauer.gwt.dnd:gwt-dnd:3.2.0" level="project" />  http://mvnrepository.com/artifact/com.allen-sauer.gwt.dnd/gwt-dnd/3.3.3 gwt-user 2.6.0
 com.google.gwt.inject:gin:2.1.2" level="project" />  -- http://mvnrepository.com/artifact/com.google.gwt.inject/gin/2.1.2  depends on gwt-user2.5
 com.tractionsoftware:gwt-traction:1.6.0" level="project" /> --   depends on gwt-user2.6.1, gwt-servlet 2.6.1
 
because of which - whenever I run my project i see multiple versions of gwt-user, gwt-dev getting pulled in. I somehow feel that the conflicting versions are the problem here ( https://groups.google.com/forum/#!topic/google-web-toolkit/KhDcOi_69tU)

Any idea?? Is there any way to stop the multiple versions ? How do i set up in the classpath?
